### ISSUE TITLE
Configure CI to run tests

### ISSUE THREAD

**Issue by mfeliu** [plexil-rwl-support/PLEXIL5#20]
Alejandro, I think you are more familiar with configuring the CI. Could you configure this repository to run the semantics'  and the parsers' tests every time changes are pushed?

**Comment by ajjimenezm** [comment]
Yes, I am on it

**Comment by ajjimenezm** [comment]
@mfeliu  I am currently working on trying to get the pipeline to properly execute ./runTests.sh . However I am getting lots of errors in the pipeline when executing it, such as import errors and Unexpected token errors, but this should not be happening because the tests are working on my machine. My question is, was there any previous set up step to get ./runTests.sh working properly? Maybe loading some file or getting some package.

Additionally I wanted to ask you if the -v flag used in the bash script is necessary, because it is giving some problems too.

**Comment by ajjimenezm** [comment]
I can mimic the execution environment because I created the docker image that CircleCI is using locally.  In fact I tried to execute the tests from a local container and I was getting the same errors than in the pipeline so most definitely there is something wrong with the image.

I will compare Maude versions in a container and in my machine and see if  they are the same.

In case this is not the problem do you have any other ideas that could be causing the issue?

**Comment by mfeliu** [comment]
No, but please share the dockerfile and the full logs with the errors if you get stuck, and I will be able to dig into it on my end.

**Comment by ajjimenezm** [comment]
I have checked and Maude versions in my machine and in the container differ, it should have the 3.1 version but it actually has the 2.7. 

However, I am getting a lot of issues trying to install the 3.1 version in the container, because even though I get the .zip files decompressed, I am not being able to get the "maude" command working. Was there any simpler way to get the 3.1 version?

**Comment by ajjimenezm** [comment]
I already got the image figured out and the tests run okay, it was indeed an error with the version (the container had 2.7 and 3.1 was necessary). It gave me a bit of a headache to get the version working but now everything is fine.

The last challenge I am facing is modifying both runTests.sh and runAT.sh because the way they are implemented now, when you execute them they give you a result but the execution stays suspended until you exit manually with ctrl+c. Ideally the tests would throw an exit code 1 whenever there is some mistake, or maybe I could check the results if they are stored somewhere in a file and throw it afterwards. It is important to throw an error so that the pipeline reports it. 

How would you approach this @mfeliu ?

**Comment by mfeliu** [comment]
Just change the files so that they only execute the tests once. The code of the script should be much simpler like that. My guess is that you will only have to change the `runAT.sh` and the `runTests.sh` scripts, but not the ones called by them.
