### ISSUE TITLE
semantics: Add non-deterministic generators

### ISSUE THREAD

**Issue by mikedalal** [plexil-rwl-support/PLEXIL5#26]
There are some prototypical non-deterministic environment generators in the GitLab version of this repo (e.g. I was experimenting with `commandAckGeneratorEx`), and any such generators that are usable would be very useful to include in this one.

**Comment by mfeliu** [comment]
I have a proposal to make this issue more concrete. Since in the code base there are many generators whose behavior (and their correctness) is not easy to assess, what do you think if I start documenting all the generators that are currently provided in PLEXILITE so that we can pinpoint their limitations? In this way, we will be able to extend them, compare them with the the "abandoned ones", etc.

**Comment by mikedalal** [comment]
Sounds good, @mfeliu .  I was only aware of the deterministic generator.

**Comment by mikedalal** [comment]
I have reviewed the all the open Issues and PRs, and this one is highest priority for the Ames CIF project!
