### ISSUE TITLE
ci: semantics: Support the regression tests in the CI

### ISSUE THREAD

**Issue by mfeliu** [plexil-rwl-support/PLEXIL5#33]
Needs:
- Tracking all the regression tests that are currently passing
- CI checking that the passing regression tests coincides with the tracked ones. Otherwise signal an error so that the "current tracking" is updated at the same commit

**Comment by ajjimenezm** [comment]
Hello @mfeliu I have encountered a problem that I was sure I was going to face when you presented me the idea of checking regression tests.

 The problem is that in the regression script we are accessing the plexil original plans directly from the original repository as a submodule. This is a problem for the pipeline since it cannot access that code given that it comes from a different repository (probably it could, but I do not think they are giving us enough permissions for it too be viable).

I have thought that maybe we could avoid this by simply uploading the the parsed plans and scripts to the repository too. In this way I would create a flag for the regression script in order to have a special way of execution for the pipeline (where it does not access the original files at all). This solution is not optimal so I am writing this in order to get different ideas from you to approach this issue.

**Comment by mfeliu** [comment]
Do you think this https://discuss.circleci.com/t/automatically-load-git-submodules/159/9 might help?

**Comment by ajjimenezm** [comment]
It could be a good solution, I thought we were going to need some permissions but it does not seem like it. 

I am going to add a new flag for the pipeline execution, and in this flag I am going to include a check for the test LibraryCallWithArray, since this test generates an infinite loop of MACRO and does not allow the pipeline to finish execution. Let me know when this test no longer generates this problem so that I can remove this additional check.

**Comment by mfeliu** [comment]
It would be better if you introduced a timeout only for the execution of each test (Maude and Executive). Since this plans are very short.

**Comment by ajjimenezm** [comment]
I have implemented what you have requested and now everything seems to be working fine, at least workflow wise, you can take a look if you wish.

Now the problem is that I am getting different results in the pipeline and in my workstation, so I do not know what to trust. For example repeat6.plx does not seem in the pipeline but command5 does (opposite to my computer).

**Comment by mfeliu** [comment]
When I try to check any regression test I get something like:
```
--------------------------------array2.maude--------------------------------
EQ
Traceback (most recent call last):
  File "/Users/mfeliuga/Desktop/projects/sws/plexil/rwl-semantics/PLEXIL5.github/semantics/test/regression/runRegression.py", line 170, in <module>
    main()
  File "/Users/mfeliuga/Desktop/projects/sws/plexil/rwl-semantics/PLEXIL5.github/semantics/test/regression/runRegression.py", line 167, in main
    runRegression()
  File "/Users/mfeliuga/Desktop/projects/sws/plexil/rwl-semantics/PLEXIL5.github/semantics/test/regression/runRegression.py", line 55, in runRegression
    raise Exception('Test ' + str(line) + ' failed')
Exception: Test UpdateLookupTest.maude failed
```
Can you please fix this so that the default behavior of the script is the same as before?

**Comment by ajjimenezm** [comment]
> When I try to check any regression test I get something like:
> 
> ```
> --------------------------------array2.maude--------------------------------
> EQ
> Traceback (most recent call last):
>   File "/Users/mfeliuga/Desktop/projects/sws/plexil/rwl-semantics/PLEXIL5.github/semantics/test/regression/runRegression.py", line 170, in <module>
>     main()
>   File "/Users/mfeliuga/Desktop/projects/sws/plexil/rwl-semantics/PLEXIL5.github/semantics/test/regression/runRegression.py", line 167, in main
>     runRegression()
>   File "/Users/mfeliuga/Desktop/projects/sws/plexil/rwl-semantics/PLEXIL5.github/semantics/test/regression/runRegression.py", line 55, in runRegression
>     raise Exception('Test ' + str(line) + ' failed')
> Exception: Test UpdateLookupTest.maude failed
> ```
> 
> Can you please fix this so that the default behavior of the script is the same as before?

Are you sure you have downloaded the latest changes? Yesterday I updated the script so that the checking of regression tests only takes place when you use the --pipeline flag. If you have done so let me know so I can look further into it. 

Also, have you change anything within the repository, maybe with permissions? Because the pipeline is not triggering now and I do not know why since I have not done anything today.

**Comment by ajjimenezm** [comment]
@mfeliu everything is working fine now, I have solved the errors related to the disparity of results by simply deleting all the changes I had locally in the PLEXIL submodule, it seems that I had done some modifications during this time.

I am going to open a Pull Request now so that you can review the code easily and suggest whatever changes you consider necessary. Once everything is good I will squash all the commits and give them an appropiate name.
